package ac.affd_android.affdview;

/**
 * Created by ac on 4/28/16.
 *
 */
public interface Constant {
    int PRE_SPLIT_TRIANGLE_SIZE = 112;
    int PRE_SPLIT_POINT_SIZE = 48;

    //平均每条边分成4 × 4 × 4段
    int F = 1;
    int PRE_SPLIT_TRIANGLE_NUMBER = F * F;
    int PRE_SPLIT_POINT_NUMBER = (2 + F) * (F + 1) / 2;

    int PRE_SPLIT_TOTAL_SIZE = (PRE_SPLIT_TRIANGLE_NUMBER * PRE_SPLIT_TRIANGLE_SIZE
            + PRE_SPLIT_POINT_NUMBER * PRE_SPLIT_POINT_SIZE) * 2;

    int POINT_SIZE = (3 + 3 + 2) * 4;
    int POINT_SIZE_P3T1_OFFSET = 0;
    int POINT_SIZE_N3T1_OFFSET = 16;
    int TRIANGLE_POINT_SIZE = 3 * POINT_SIZE;
    int TRIANGLE_PARAMETER_SIZE = 3 * 16;
    int PN_TRIANGLE_SIZE = (10 + 6) * 4 * 4;
    int TRIANGLE_INDEX_SIZE = 3 * 4;
    int VEC4_BYTE_SIZE = 4 * 4;

    boolean DEBUG_SWITCH = true;
    boolean ACTIVE_DEBUG_BUFFER = true;

    int MV_MATRIX_LOCATION = 0;
    int MVP_MATRIX_LOCATION = 1;
    int ATTR1_LOCATION = 0;
    int ATTR2_LOCATION = 1;
    int PRE_COMPUTE_INPUT_BINDING_POINT = 0;
    int RENDERER_POINT_BINDING_POINT = 1;
    int RENDERER_INDEX_BINDING_POINT = 2;
    int SPLIT_RESULT_BINDING_POINT = 5;
    int BSPLINEBODY_SAMPLE_POINT_BINDING_POINT = 0;
    int BSPLINEBODY_INFO_BINDING_POINT = 1;
    int TESSELLATION_INFO_BINDING_POINT = 2;
    int TESSELLATION_ORIGINAL_PARAMETER_BINDING_POINT = 6;
    int SELECT_RESULT_BINDING_POINT = 7;
    int DEBUG_BINDING_POINT = 16;
    int MAX_TESSELLATION_POINT_NUMBER = 66;
    int MAX_TESSELLATION_TRIANGLE_NUMBER = 100;
    int SPLIT_ATOMIC_BINDING_POINT = 0;
    int SELECT_RESULT_ATOMIC_BINDING_POINT = 1;

    String PATTERN_DATA_LEVEL = "level";
    String PATTERN_DATA_OFFSETS_AND_LENGTHS = "offsets_and_lengths";
    String PATTERN_DATA_POINTS = "points";
    String PATTERN_DATA_TRIANGLES = "triangles";
    String PATTERN_DATA_PARAMETERS = "parameters";
    float ZERO = 0.000001f;
}
